CREATE DATABASE onlineshop
GO
USE master
GO
DROP DATABASE onlineshop
GO
USE onlineshop
GO
CREATE TABLE Category
(
	Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	CategoryName NVARCHAR(100) NOT NULL CHECK(CategoryName <> N'') UNIQUE
);
CREATE TABLE Type
(
	Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	TypeName NVARCHAR(100) NOT NULL CHECK(TypeName <> N''),
	CategoryId INT FOREIGN KEY REFERENCES Category(Id)
);
CREATE TABLE Model
(
	Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	ModelName NVARCHAR(100) NOT NULL CHECK(ModelName <> N''),
	TypeId INT FOREIGN KEY REFERENCES Type(Id)
);
CREATE TABLE Product
(
	Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	Price MONEY NOT NULL CHECK(Price >=0.0),
	Availability INT CHECK(Availability >=0),
	UrlPhoto NVARCHAR(100) NOT NULL CHECK(UrlPhoto <> N''),
	ModelId INT FOREIGN KEY REFERENCES Model(Id)
);
CREATE TABLE Characteristics
(
	Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	CharacteristicName NVARCHAR(100) NOT NULL CHECK(CharacteristicName <> N'') UNIQUE,
);
CREATE TABLE UnitOfMeasurement
(
	Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	Unit NVARCHAR(20) NOT NULL CHECK(Unit <> N''),
);
CREATE TABLE CharacteristicValue
(
	Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	Value FLOAT NOT NULL UNIQUE,
);
CREATE TABLE Descriotion
(
	Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	ProductId INT FOREIGN KEY REFERENCES Product(Id),
	CharacteristicId INT FOREIGN KEY REFERENCES Characteristics(Id),
	CharacteristicValueId INT FOREIGN KEY REFERENCES CharacteristicValue(Id),
	UnitOfMeasurementId INT FOREIGN KEY REFERENCES UnitOfMeasurement(Id)
);
CREATE TABLE Region
(
	Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	RegionName NVARCHAR(100) NOT NULL CHECK(RegionName <> N'')
);
CREATE TABLE Rights
(
	Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	RightsName NVARCHAR(100) NOT NULL CHECK(RightsName <> N'')
);
CREATE TABLE Transport
(
	Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	TransportName NVARCHAR(100) NOT NULL CHECK(TransportName <> N'')
);
CREATE TABLE DeliveryMethod
(
	Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	DeliveryMethodName NVARCHAR(100) NOT NULL CHECK(DeliveryMethodName <> N'')
);
CREATE TABLE Client
(
	Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	ClientName NVARCHAR(100) NOT NULL CHECK(ClientName <> N''),
	Phone NVARCHAR(20) NOT NULL CHECK(Phone <> N''),
	Town NVARCHAR(20) NOT NULL CHECK(Town <> N''),
	Street NVARCHAR(20) NOT NULL CHECK(Street <> N''),
	House INT NOT NULL,
	Apartment INT NOT NULL,
	RegionId INT FOREIGN KEY REFERENCES Region(Id)
);
CREATE TABLE Users
(
	Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	ClientId INT FOREIGN KEY REFERENCES Client(Id),
	RightsId INT FOREIGN KEY REFERENCES Rights(Id)
);
CREATE TABLE Registration
(
	Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	RegistrationData DATE NOT NULL,
	Login NVARCHAR(20) NOT NULL CHECK(Login <> N''),
	Mail NVARCHAR(40) NOT NULL CHECK(Mail <> N''),
	Pasword NVARCHAR(40) NOT NULL CHECK(Pasword <> N''),
	LastLoginDate DATE NOT NULL,
	UserId INT FOREIGN KEY REFERENCES Users(Id)
);
CREATE TABLE Status
(
	Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	Status BIT NOT NULL,
);
CREATE TABLE Orders
(
	Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	OrderDate DATE NOT NULL,
	ModificationDate DATE NOT NULL,
	Coments NVARCHAR(MAX) NOT NULL CHECK(Coments <> N''),
	DeliveryDate DATE NOT NULL,
	UserID INT FOREIGN KEY REFERENCES Users(Id),
	TransporsID INT FOREIGN KEY REFERENCES Transport(Id),
	DeliveryMethodID INT FOREIGN KEY REFERENCES DeliveryMethod(Id),
);
CREATE TABLE ShoppingCart
(
	Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	ProdutId INT FOREIGN KEY REFERENCES Product(Id),
	Quantyty INT NOT NULL,
	OrderId INT FOREIGN KEY REFERENCES Orders(Id)
);
CREATE TABLE OrderHistory
(
	Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	StatusId INT FOREIGN KEY REFERENCES Status(Id),
	OrderId INT FOREIGN KEY REFERENCES Orders(Id)
);